[display]
width = 28
height = 26

[signals]
# The 5 Space Age qualities
qualities = ["normal", "uncommon", "rare", "epic", "legendary"]

[reserved]
# Use this for your global animation frame synchronization
clock_signal = "signal-clock"
# Reserve a signal for loudness if you aren't using a full signal matrix for it
loudness_signal = "signal-info" 
